user swtdb;

drop table IF EXISTS test_zpayment_view_def ;
CREATE TABLE test_zpayment_view_def(
	ID 				INT   			NOT NULL DEFAULT 0,
	CACHE_NM		VARCHAR(128) 	NOT NULL DEFAULT '',
	CACHE_INDEX		INT			 	NOT NULL DEFAULT 0,
	LOAD_TYPE		INT		 		NOT NULL DEFAULT 0,
	DATA_TYPE		INT		 		NOT NULL DEFAULT 0,
	INDEX_COLUMNS	VARCHAR(128) 	NOT NULL DEFAULT '',
	RELATED_COLUMNS	VARCHAR(128) 	NOT NULL DEFAULT '',
	QUERY_TYPE		INT		 		NOT NULL DEFAULT 0,
	TABLE_NM		VARCHAR(128) 	NOT NULL DEFAULT '',
	LOAD_SQL		VARCHAR(256) 	NOT NULL DEFAULT '',
	COND_SQL		VARCHAR(128) 	NOT NULL DEFAULT '',
	PRIMARY KEY (id)  
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO test_zpayment_view_def (ID,CACHE_NM,CACHE_INDEX,LOAD_TYPE,DATA_TYPE,INDEX_COLUMNS,QUERY_TYPE,TABLE_NM) VALUES(1,'com.zpayment.cmn.persistent.DBUser',1,1,1,'name',0,'user')